// debe haber más variables definidas que el número de ramas, no puedo definirlas con bucle si deben estar al comienzo?
var r=new Array();
r[0]=new Array();
r[1]=new Array();
r[2]=new Array();
r[3]=new Array();
r[4]=new Array();
r[5]=new Array();
r[6]=new Array();
r[7]=new Array();
r[8]=new Array();
r[9]=new Array();
// debe haber más variables definidas que el doble del número de ramas, no puedo definirlas con bucle si deben estar al comienzo?
var poslinea=new Array();
poslinea[0]=new Array();
poslinea[1]=new Array();
poslinea[2]=new Array();
poslinea[3]=new Array();
poslinea[4]=new Array();
poslinea[5]=new Array();
poslinea[6]=new Array();
poslinea[7]=new Array();
poslinea[8]=new Array();
poslinea[9]=new Array();
poslinea[10]=new Array();
poslinea[11]=new Array();
poslinea[12]=new Array();
poslinea[13]=new Array();
poslinea[14]=new Array();
poslinea[15]=new Array();
poslinea[16]=new Array();
poslinea[17]=new Array();
poslinea[18]=new Array();
poslinea[19]=new Array();
poslinea[20]=new Array();
poslinea[21]=new Array();
poslinea[22]=new Array();
poslinea[23]=new Array();
poslinea[24]=new Array();
poslinea[25]=new Array();

var rama=new Array();
// rama[i]=new Array()
// rama[i][0] = "nombre de la rama"
// rama[i][1] = subramas;
// rama[i][2] = new Array Ramas hijas;
// rama[i][3] = descripció
// rama[i][4] =data inici
// rama[i][5] =data final
// rama[i][6] = aplicacions
// rama[i][7]= new Array
// rama[i][7][j]= matematics/data
// rama[i][8]= new Array
// rama[i][8][j]= curiosidades/data
// rama[i][9]= nivel
// rama[i][10]= imagen.
rama[0]=new Array();
rama[0][0]="Artimètica";
rama[0][1]=new Array();
rama[0][1][0]=1;
rama[0][1][1]=2;
rama[0][1][2]=7;
rama[0][2]=new Array();
rama[0][2][0]=3;
rama[0][3]="Descripció";
rama[0][4]=-3000;
rama[0][5]=2020;
rama[0][6]="aplicacions";
rama[0][7]=new Array();
rama[0][8]=new Array();
rama[0][9]=0;
rama[0][10]="logomoeb1.png";

rama[1]=new Array();
rama[1][0]="geometria1";
rama[1][1]=new Array();
rama[1][1][0]=5;
rama[1][1][1]=6;
rama[1][2]=new Array();
rama[1][3]="Descripció";
rama[1][4]=-300;
rama[1][5]=2020;
rama[1][6]="aplicacions";
rama[1][7]=new Array();
rama[1][8]=new Array();
rama[1][9]=0;
rama[1][10]="logomoeb1.png";

rama[2]=new Array();
rama[2][0]="geometria2";
rama[2][1]=new Array();
rama[2][2]=new Array();
rama[2][3]="Descripció";
rama[2][4]=-300;
rama[2][5]=2020;
rama[2][6]="aplicacions";
rama[2][7]=new Array();
rama[2][8]=new Array();
rama[2][9]=0;
rama[2][10]="logomoeb1.png";

rama[3]=new Array();
rama[3][0]="geometria3";
rama[3][1]=new Array();
//rama[3][1][0]=8;
rama[3][2]=new Array();
rama[3][3]="Descripció";
rama[3][4]=-500;
rama[3][5]=2020;
rama[3][6]="aplicacions";
rama[3][7]=new Array();
rama[3][8]=new Array();
rama[3][9]=0;
rama[3][10]="logomoeb1.png";

rama[4]=new Array();
rama[4][0]="geometria4";
rama[4][1]=new Array();
rama[4][2]=new Array();
rama[4][3]="Descripció";
rama[4][4]=-1100;
rama[4][5]=2020;
rama[4][6]="aplicacions";
rama[4][7]=new Array();
rama[4][8]=new Array();
rama[4][9]=0;
rama[4][10]="logomoeb1.png";


rama[5]=new Array();
rama[5][0]="geometria4";
rama[5][1]=new Array();
rama[5][2]=new Array();
rama[5][3]="Descripció";
rama[5][4]=500;
rama[5][5]=2020;
rama[5][6]="aplicacions";
rama[5][7]=new Array();
rama[5][8]=new Array();
rama[5][9]=0;
rama[5][10]="logomoeb1.png";

rama[6]=new Array();
rama[6][0]="geometria4";
rama[6][1]=new Array();
rama[6][2]=new Array();
rama[6][3]="Descripció";
rama[6][4]=500;
rama[6][5]=2020;
rama[6][6]="aplicacions";
rama[6][7]=new Array();
rama[6][8]=new Array();
rama[6][9]=0;
rama[6][10]="logomoeb1.png";

rama[7]=new Array();
rama[7][0]="geometria4";
rama[7][1]=new Array();
rama[7][2]=new Array();
rama[7][3]="Descripció";
rama[7][4]=1100;
rama[7][5]=2020;
rama[7][6]="aplicacions";
rama[7][7]=new Array();
rama[7][8]=new Array();
rama[7][9]=0;
rama[7][10]="logomoeb1.png";

rama[8]=new Array();
rama[8][0]="geometria4";
rama[8][1]=new Array();
rama[8][2]=new Array();
rama[8][3]="Descripció";
rama[8][4]=1100;
rama[8][5]=2020;
rama[8][6]="aplicacions";
rama[8][7]=new Array();
rama[8][8]=new Array();
rama[8][9]=0;
rama[8][10]="logomoeb1.png";


export { r, rama };